// modules/supplier/utils/pdfGenerator.js
import PDFDocument from "pdfkit";

/**
 * Returns a Buffer containing the generated PDF
 */
export const generatePurchaseOrderPDF = async (purchase, supplier) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40 });
      const buffers = [];
      doc.on("data", buffers.push.bind(buffers));
      doc.on("end", () => resolve(Buffer.concat(buffers)));

      // Header
      doc.fontSize(18).text("HeavySync", { align: "left" });
      doc.fontSize(12).text("Purchase Order", { align: "right" });
      doc.moveDown();

      doc.fontSize(10).text(`Order ID: ${purchase.orderId}`);
      doc.text(`Date: ${new Date(purchase.createdAt).toLocaleString()}`);
      if (purchase.expectedDeliveryDate) doc.text(`Expected Delivery: ${new Date(purchase.expectedDeliveryDate).toLocaleDateString()}`);
      doc.moveDown();

      doc.text(`Supplier: ${supplier?.supplierName || "N/A"}`);
      if (supplier?.contactPerson) doc.text(`Contact Person: ${supplier.contactPerson}`);
      if (supplier?.phone) doc.text(`Phone: ${supplier.phone}`);
      if (supplier?.email) doc.text(`Email: ${supplier.email}`);
      doc.moveDown();

      // Table header
      doc.fontSize(10).text("Item", 40, doc.y, { continued: true });
      doc.text("Qty", 300, doc.y, { continued: true });
      doc.text("Unit Price", 350, doc.y, { continued: true });
      doc.text("Total", 460, doc.y);
      doc.moveDown(0.5);

      // Items
      purchase.items.forEach(it => {
        doc.text(it.itemName, 40, doc.y, { continued: true });
        doc.text(String(it.quantity), 300, doc.y, { continued: true });
        doc.text(it.unitPrice.toFixed(2), 350, doc.y, { continued: true });
        doc.text(it.total.toFixed(2), 460, doc.y);
        doc.moveDown(0.3);
      });

      doc.moveDown();
      doc.fontSize(11).text(`Total Cost: ${purchase.totalCost.toFixed(2)}`, { align: "right" });

      // Footer
      doc.moveDown(2);
      doc.fontSize(9).text("Generated by HeavySync", { align: "center" });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};